## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("aids_attendance.xlsx")
display(df)

       Roll No            Student Name  ... Last Present Date  Consecutive Absences
0    4MW23AD50               SRAJAN  S  ...             Never                    11
1   4MW24AD001       ADITHYA S POOJARY  ...        2026-10-07                     0
2   4MW24AD002  ANKITHA PRASANNA NAYAK  ...        2026-10-07                     0
3   4MW24AD003          ANUSHA KOTEGAR  ...        2026-10-07                     0
4   4MW24AD004      ANVITA RAMESH NAIK  ...        2026-10-07                     0
..         ...                     ...  ...               ...                   ...
57  4MW24AD059             ZEHA AYESHA  ...        2026-10-07                     0
58  4MW24AD060        AMITH G PALANDYE  ...             Never                    10
59  4MW24AD061      AMOGH BHASKAR NAIK  ...        2026-10-07                     0
60  4MW24AD062                CHANDISH  ...        2026-10-05                     1
61  4MW25AD400        SAMPATH S HEBBAR  ...        2026-09-02                     8

[62 rows x 12 columns]

#### Section 1: Data Inspection

In [3]:
print("First 10 rows:")
display(df.head(10))
print("\nShape:", df.shape)
print("\nData types:")
print(df.dtypes)

First 10 rows:

      Roll No            Student Name  ... Last Present Date  Consecutive Absences
0   4MW23AD50               SRAJAN  S  ...             Never                    11
1  4MW24AD001       ADITHYA S POOJARY  ...        2026-10-07                     0
2  4MW24AD002  ANKITHA PRASANNA NAYAK  ...        2026-10-07                     0
3  4MW24AD003          ANUSHA KOTEGAR  ...        2026-10-07                     0
4  4MW24AD004      ANVITA RAMESH NAIK  ...        2026-10-07                     0
5  4MW24AD005       ARPITHA M THANTRY  ...        2026-10-07                     0
6  4MW24AD007                  ASNIYA  ...        2026-10-07                     0
7  4MW24AD008   B. G PRARTHANA HEBBAR  ...        2026-10-07                     0
8  4MW24AD009      BHARATHRAJ A NAYAK  ...        2026-10-05                     1
9  4MW24AD010        BHEEMA KATTIMANI  ...        2026-10-07                     0

[10 rows x 12 columns]

Shape: (62, 12)

Data types:
Roll No                 object
Student Name            object
Subject                 object
Total Classes            int64
Present                  int64
Absent                   int64
Excused                  int64
Attendance %            object
Status                  object
Classes Needed (75%)    object
Last Present Date       object
Consecutive Absences     int64
dtype: object

In [4]:
print("Missing values in each column:")
print(df.isna().sum())
print("\nRows where Last Present Date is Never:", df["Last Present Date"].astype(str).str.strip().str.lower().eq("never").sum())

Missing values in each column:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

Rows where Last Present Date is Never: 5

In [5]:
df = df.rename(columns={"Roll No":"roll_no", "Student Name":"student_name", "Attendance %":"attendance_pct", "Total Classes":"total_classes", "Present":"present", "Absent":"absent", "Excused":"excused", "Status":"status", "Classes Needed (75%)":"classes_needed_75", "Last Present Date":"last_present_date", "Consecutive Absences":"consecutive_absences"})
print(df.columns.tolist())

['roll_no', 'student_name', 'Subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']

In [6]:
df["attendance_pct"] = pd.to_numeric(df["attendance_pct"].astype(str).str.replace("%", "", regex=False).str.strip(), errors="coerce")
df["last_present_date"] = pd.to_datetime(df["last_present_date"].replace("Never", pd.NA), errors="coerce")
print(df[["attendance_pct", "last_present_date"]].head(10))
print("\nAttendance percentage is stored on a 0–100 scale.")

   attendance_pct last_present_date
0               0               NaT
1              64        2026-10-07
2             100        2026-10-07
3              91        2026-10-07
4              82        2026-10-07
5              73        2026-10-07
6              91        2026-10-07
7              91        2026-10-07
8              36        2026-10-05
9              73        2026-10-07

Attendance percentage is stored on a 0–100 scale.

#### Section 2: Filtering & Selection

In [7]:
critical = df.loc[df["status"].eq("Critical")].sort_values("attendance_pct", ascending=True)
display(critical)

       roll_no  ... consecutive_absences
0    4MW23AD50  ...                   11
52  4MW24AD054  ...                   10
58  4MW24AD060  ...                   10
36  4MW24AD037  ...                   10
45  4MW24AD046  ...                   10
61  4MW25AD400  ...                    8
26  4MW24AD027  ...                    1
30  4MW24AD031  ...                    0
8   4MW24AD009  ...                    1
31  4MW24AD032  ...                    1
37  4MW24AD038  ...                    1
59  4MW24AD061  ...                    0
10  4MW24AD011  ...                    0
41  4MW24AD042  ...                    1
55  4MW24AD057  ...                    0
60  4MW24AD062  ...                    1
17  4MW24AD018  ...                    0
18  4MW24AD019  ...                    0
19  4MW24AD020  ...                    0
13  4MW24AD014  ...                    0
1   4MW24AD001  ...                    0
23  4MW24AD024  ...                    0
56  4MW24AD058  ...                    0
40  4MW24AD041  ...                    0
24  4MW24AD025  ...                    0
21  4MW24AD022  ...                    0
20  4MW24AD021  ...                    0
16  4MW24AD017  ...                    0
9   4MW24AD010  ...                    0
5   4MW24AD005  ...                    0
11  4MW24AD012  ...                    0
25  4MW24AD026  ...                    0

[32 rows x 12 columns]

In [8]:
fully_absent = df.loc[df["present"].eq(0), ["roll_no", "student_name", "consecutive_absences"]]
display(fully_absent)

       roll_no            student_name  consecutive_absences
0    4MW23AD50               SRAJAN  S                    11
36  4MW24AD037  RISHAN FRANCIS MENEZES                    10
45  4MW24AD046           SHARANU PATIL                    10
52  4MW24AD054                UJWAL. K                    10
58  4MW24AD060        AMITH G PALANDYE                    10

In [9]:
print("(a) Safe students using .loc:")
display(df.loc[df["status"].eq("Safe")])
print("(b) First 15 rows and columns 2–6 using .iloc:")
display(df.iloc[:15, 1:6])

(a) Safe students using .loc:

       roll_no             student_name  ... last_present_date  consecutive_absences
2   4MW24AD002   ANKITHA PRASANNA NAYAK  ...        2026-10-07                     0
3   4MW24AD003           ANUSHA KOTEGAR  ...        2026-10-07                     0
6   4MW24AD007                   ASNIYA  ...        2026-10-07                     0
7   4MW24AD008    B. G PRARTHANA HEBBAR  ...        2026-10-07                     0
14  4MW24AD015              K MANYA RAO  ...        2026-10-07                     0
15  4MW24AD016                    KAVYA  ...        2026-10-07                     0
28  4MW24AD029        PRATHEEKSHA NAYAK  ...        2026-10-07                     0
32  4MW24AD033            PRIYADARSHINI  ...        2026-10-07                     0
33  4MW24AD034  RAKSHITHA (ASHOK KUMAR)  ...        2026-10-07                     0
35  4MW24AD036            RAMITHA R RAO  ...        2026-10-07                     0
39  4MW24AD040                   SAKSHI  ...        2026-10-07                     0
42  4MW24AD043         SANJANA A MOOLYA  ...        2026-10-05                     1
43  4MW24AD044          SANVI SHETTIGAR  ...        2026-10-07                     0
44  4MW24AD045                 SHARADHI  ...        2026-10-07                     0
46  4MW24AD047       SHETTY RAKSHA UDAY  ...        2026-10-07                     0
47  4MW24AD048           SHRADDHA NAYAK  ...        2026-10-07                     0
48  4MW24AD049                  SHRAVYA  ...        2026-10-05                     1
49  4MW24AD050         SHRI RAKSHA BHAT  ...        2026-10-07                     0
50  4MW24AD052            TASMIYA ANJUM  ...        2026-10-07                     0
51  4MW24AD053                  THRISHA  ...        2026-10-07                     0
53  4MW24AD055         VAISHNAVI K AMIN  ...        2026-10-07                     0
54  4MW24AD056       VANDANA V DEVADIGA  ...        2026-10-07                     0
57  4MW24AD059              ZEHA AYESHA  ...        2026-10-07                     0

[23 rows x 12 columns]

(b) First 15 rows and columns 2–6 using .iloc:

                 student_name  ... absent
0                   SRAJAN  S  ...     11
1           ADITHYA S POOJARY  ...      4
2      ANKITHA PRASANNA NAYAK  ...      0
3              ANUSHA KOTEGAR  ...      1
4          ANVITA RAMESH NAIK  ...      2
5           ARPITHA M THANTRY  ...      3
6                      ASNIYA  ...      1
7       B. G PRARTHANA HEBBAR  ...      1
8          BHARATHRAJ A NAYAK  ...      7
9            BHEEMA KATTIMANI  ...      3
10                      BINDU  ...      5
11            CHIRAG N KUNDER  ...      3
12                     DHANYA  ...      2
13  GOURISH VENKATRAMAN MOGER  ...      4
14                K MANYA RAO  ...      1

[15 rows x 5 columns]

In [10]:
display(df.loc[df["consecutive_absences"].ge(5), ["student_name", "status", "last_present_date"]])

              student_name    status last_present_date
0                SRAJAN  S  Critical               NaT
36  RISHAN FRANCIS MENEZES  Critical               NaT
45           SHARANU PATIL  Critical               NaT
52                UJWAL. K  Critical               NaT
58        AMITH G PALANDYE  Critical               NaT
61        SAMPATH S HEBBAR  Critical        2026-09-02

### Section 3: Grouping & Aggregation

In [11]:
status_summary = df.groupby("status").agg(student_count=("roll_no", "count"), average_attendance_pct=("attendance_pct", "mean"), max_consecutive_absences=("consecutive_absences", "max"))
display(status_summary)

          student_count  average_attendance_pct  max_consecutive_absences
status
Critical             32               49.875000                        11
Safe                 23               94.086957                         1
Warning               7               81.428571                         1

In [12]:
df["attendance_category"] = pd.cut(df["attendance_pct"], bins=[-0.01, 59.999, 74.999, 89.999, 100], labels=["Poor", "Average", "Good", "Excellent"], include_lowest=True)
print(df.groupby("attendance_category", observed=False).size().rename("student_count"))

attendance_category
Poor         13
Average      19
Good          7
Excellent    23
Name: student_count, dtype: int64

In [13]:
totals = pd.Series({"total_classes_conducted": df["total_classes"].sum(), "total_present": df["present"].sum(), "total_absent": df["absent"].sum()})
display(totals)

total_classes_conducted    650
total_present              454
total_absent               196
dtype: int64

In [14]:
display(df.groupby("status").agg(present_min=("present", "min"), present_max=("present", "max"), present_mean=("present", "mean"), absent_sum=("absent", "sum")))

          present_min  present_max  present_mean  absent_sum
status
Critical            0            8      5.312500         168
Safe                9           11      9.695652          14
Warning             8            9      8.714286          14

### Section 4: Feature Engineering & Transformation

In [15]:
df["risk_score"] = (df["absent"] * 0.4) + (df["consecutive_absences"] * 0.6)
display(df.nlargest(10, "risk_score")[["roll_no", "student_name", "absent", "consecutive_absences", "risk_score"]])

       roll_no            student_name  ...  consecutive_absences  risk_score
0    4MW23AD50               SRAJAN  S  ...                    11        11.0
36  4MW24AD037  RISHAN FRANCIS MENEZES  ...                    10        10.0
45  4MW24AD046           SHARANU PATIL  ...                    10        10.0
52  4MW24AD054                UJWAL. K  ...                    10        10.0
58  4MW24AD060        AMITH G PALANDYE  ...                    10        10.0
61  4MW25AD400        SAMPATH S HEBBAR  ...                     8         8.4
26  4MW24AD027                 PRAJWAL  ...                     1         3.8
8   4MW24AD009      BHARATHRAJ A NAYAK  ...                     1         3.4
30  4MW24AD031         PRAVEEN KUMAR N  ...                     0         2.8
31  4MW24AD032           PREETH SHETTY  ...                     1         2.6

[10 rows x 5 columns]

In [16]:
df["classes_needed_numeric"] = pd.to_numeric(df["classes_needed_75"].astype(str).str.extract(r"(\d+)")[0], errors="coerce").fillna(0).astype(int)
display(df[["classes_needed_75", "classes_needed_numeric"]].head(15))

   classes_needed_75  classes_needed_numeric
0            33 more                      33
1             5 more                       5
2              ✓ Met                       0
3              ✓ Met                       0
4              ✓ Met                       0
5             1 more                       1
6              ✓ Met                       0
7              ✓ Met                       0
8            17 more                      17
9             1 more                       1
10            9 more                       9
11            1 more                       1
12             ✓ Met                       0
13            5 more                       5
14             ✓ Met                       0

In [17]:
df["attendance_flag"] = df["attendance_pct"].apply(lambda x: "Defaulter" if x < 75 else "Safe")
display(df[["student_name", "attendance_pct", "attendance_flag"]])

              student_name  attendance_pct attendance_flag
0                SRAJAN  S               0       Defaulter
1        ADITHYA S POOJARY              64       Defaulter
2   ANKITHA PRASANNA NAYAK             100            Safe
3           ANUSHA KOTEGAR              91            Safe
4       ANVITA RAMESH NAIK              82            Safe
..                     ...             ...             ...
57             ZEHA AYESHA              90            Safe
58        AMITH G PALANDYE               0       Defaulter
59      AMOGH BHASKAR NAIK              50       Defaulter
60                CHANDISH              60       Defaulter
61        SAMPATH S HEBBAR              10       Defaulter

[62 rows x 3 columns]

In [18]:
df["attendance_range"] = pd.cut(df["attendance_pct"], bins=[0, 50, 75, 90, 100], labels=["Critical", "Warning", "Good", "Excellent"], include_lowest=True, right=True)
display(df[["student_name", "attendance_pct", "attendance_range"]])

              student_name  attendance_pct attendance_range
0                SRAJAN  S               0         Critical
1        ADITHYA S POOJARY              64          Warning
2   ANKITHA PRASANNA NAYAK             100        Excellent
3           ANUSHA KOTEGAR              91        Excellent
4       ANVITA RAMESH NAIK              82             Good
..                     ...             ...              ...
57             ZEHA AYESHA              90             Good
58        AMITH G PALANDYE               0         Critical
59      AMOGH BHASKAR NAIK              50         Critical
60                CHANDISH              60          Warning
61        SAMPATH S HEBBAR              10         Critical

[62 rows x 3 columns]

### Section 5: Advanced Analysis

In [19]:
pivot = pd.pivot_table(df, index="status", columns="attendance_category", values="roll_no", aggfunc="count", fill_value=0, observed=False)
display(pivot)

attendance_category  Poor  Average  Good  Excellent
status
Critical               13       19     0          0
Safe                    0        0     0         23
Warning                 0        0     7          0

In [20]:
df["base_name"] = df["student_name"].astype(str).str.strip().str.upper().str.split().str[0].str.replace(r"[^A-Z]", "", regex=True)
duplicate_bases = df["base_name"].duplicated(keep=False)
display(df.loc[duplicate_bases].sort_values("base_name", na_position="last"))

       roll_no         student_name  ... attendance_range  base_name
18  4MW24AD019       MOHAMMED SUHAN  ...          Warning   MOHAMMED
19  4MW24AD020      MOHAMMED AFREED  ...          Warning   MOHAMMED
20  4MW24AD021  MOHAMMED AWAD TONSE  ...          Warning   MOHAMMED
24  4MW24AD025           PAVAN BHAT  ...          Warning      PAVAN
25  4MW24AD026      PAVAN S POOJARY  ...          Warning      PAVAN

[5 rows x 18 columns]

In [21]:
# Hypothetical details for demonstrating an inner join; replace these sample values if your instructor specifies others.
student_details = pd.DataFrame({
    "Roll No": df["roll_no"].drop_duplicates(),
    "Branch": "AI&DS",
    "Semester": "Not specified"
})
merged = df.merge(student_details, left_on="roll_no", right_on="Roll No", how="inner")
display(merged)

       roll_no            student_name  ... Branch       Semester
0    4MW23AD50               SRAJAN  S  ...  AI&DS  Not specified
1   4MW24AD001       ADITHYA S POOJARY  ...  AI&DS  Not specified
2   4MW24AD002  ANKITHA PRASANNA NAYAK  ...  AI&DS  Not specified
3   4MW24AD003          ANUSHA KOTEGAR  ...  AI&DS  Not specified
4   4MW24AD004      ANVITA RAMESH NAIK  ...  AI&DS  Not specified
..         ...                     ...  ...    ...            ...
57  4MW24AD059             ZEHA AYESHA  ...  AI&DS  Not specified
58  4MW24AD060        AMITH G PALANDYE  ...  AI&DS  Not specified
59  4MW24AD061      AMOGH BHASKAR NAIK  ...  AI&DS  Not specified
60  4MW24AD062                CHANDISH  ...  AI&DS  Not specified
61  4MW25AD400        SAMPATH S HEBBAR  ...  AI&DS  Not specified

[62 rows x 21 columns]

In [1]:
df.to_csv("attendance_analytics_completed.csv", index=False)
df.loc[df["status"].eq("Critical")].to_csv("critical_students.csv", index=False)
status_summary.to_csv("status_summary.csv")
df.nlargest(10, "risk_score").to_csv("top_10_risk_students.csv", index=False)
print("Exported: attendance_analytics_completed.csv, critical_students.csv, status_summary.csv, top_10_risk_students.csv")

NameError: name 'df' is not defined